// Generated by gencpp from file ros_arduino_msgs/AnalogPinMode.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_ANALOGPINMODE_H
#define ROS_ARDUINO_MSGS_MESSAGE_ANALOGPINMODE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/AnalogPinModeRequest.h>
#include <ros_arduino_msgs/AnalogPinModeResponse.h>


namespace ros_arduino_msgs
{

struct AnalogPinMode
{

typedef AnalogPinModeRequest Request;
typedef AnalogPinModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnalogPinMode
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogPinMode > {
  static const char* value()
  {
    return "b10eff5e5e7e4623e1ee840cec92b372";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogPinMode&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::AnalogPinMode > {
  static const char* value()
  {
    return "ros_arduino_msgs/AnalogPinMode";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogPinMode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogPinModeRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogPinMode >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogPinModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogPinModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogPinModeRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogPinMode >
template<>
struct DataType< ::ros_arduino_msgs::AnalogPinModeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogPinModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogPinModeResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogPinMode >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogPinModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogPinModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogPinModeResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogPinMode >
template<>
struct DataType< ::ros_arduino_msgs::AnalogPinModeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogPinModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_ANALOGPINMODE_H
