// Generated by gencpp from file ros_arduino_msgs/AnalogSensorWrite.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORWRITE_H
#define ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORWRITE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/AnalogSensorWriteRequest.h>
#include <ros_arduino_msgs/AnalogSensorWriteResponse.h>


namespace ros_arduino_msgs
{

struct AnalogSensorWrite
{

typedef AnalogSensorWriteRequest Request;
typedef AnalogSensorWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnalogSensorWrite
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorWrite > {
  static const char* value()
  {
    return "6e68bf91459258a84dab807f5c768df7";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogSensorWrite&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorWrite > {
  static const char* value()
  {
    return "ros_arduino_msgs/AnalogSensorWrite";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogSensorWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorWriteRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorWrite >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogSensorWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorWriteRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorWrite >
template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogSensorWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorWriteResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorWrite >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogSensorWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorWriteResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorWrite >
template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogSensorWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORWRITE_H
