// Generated by gencpp from file ros_arduino_msgs/AnalogSensorRead.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORREAD_H
#define ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORREAD_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/AnalogSensorReadRequest.h>
#include <ros_arduino_msgs/AnalogSensorReadResponse.h>


namespace ros_arduino_msgs
{

struct AnalogSensorRead
{

typedef AnalogSensorReadRequest Request;
typedef AnalogSensorReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnalogSensorRead
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorRead > {
  static const char* value()
  {
    return "6e68bf91459258a84dab807f5c768df7";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogSensorRead&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorRead > {
  static const char* value()
  {
    return "ros_arduino_msgs/AnalogSensorRead";
  }

  static const char* value(const ::ros_arduino_msgs::AnalogSensorRead&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorReadRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorRead >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorReadRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorRead >
template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorReadRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorReadResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::AnalogSensorRead >
template<>
struct MD5Sum< ::ros_arduino_msgs::AnalogSensorReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::AnalogSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorReadResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::AnalogSensorRead >
template<>
struct DataType< ::ros_arduino_msgs::AnalogSensorReadResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::AnalogSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::AnalogSensorReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_ANALOGSENSORREAD_H
