// Generated by gencpp from file ros_arduino_msgs/DigitalSensorPinMode.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODE_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/DigitalSensorPinModeRequest.h>
#include <ros_arduino_msgs/DigitalSensorPinModeResponse.h>


namespace ros_arduino_msgs
{

struct DigitalSensorPinMode
{

typedef DigitalSensorPinModeRequest Request;
typedef DigitalSensorPinModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalSensorPinMode
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorPinMode > {
  static const char* value()
  {
    return "8ed8b14a7df13f0c44543de998e53af4";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinMode&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorPinMode > {
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalSensorPinMode";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinMode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorPinModeRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorPinMode >
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorPinModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorPinModeRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorPinMode >
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorPinModeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorPinModeResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorPinMode >
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorPinModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorPinModeResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorPinMode >
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorPinModeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorPinMode >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODE_H
