// Generated by gencpp from file ros_arduino_msgs/DigitalSensorPinModeRequest.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODEREQUEST_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_arduino_msgs
{
template <class ContainerAllocator>
struct DigitalSensorPinModeRequest_
{
  typedef DigitalSensorPinModeRequest_<ContainerAllocator> Type;

  DigitalSensorPinModeRequest_()
    : direction(false)  {
    }
  DigitalSensorPinModeRequest_(const ContainerAllocator& _alloc)
    : direction(false)  {
  (void)_alloc;
    }



   typedef uint8_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DigitalSensorPinModeRequest_

typedef ::ros_arduino_msgs::DigitalSensorPinModeRequest_<std::allocator<void> > DigitalSensorPinModeRequest;

typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorPinModeRequest > DigitalSensorPinModeRequestPtr;
typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorPinModeRequest const> DigitalSensorPinModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator1> & lhs, const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator1> & lhs, const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_arduino_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ed8b14a7df13f0c44543de998e53af4";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ed8b14a7df13f0cULL;
  static const uint64_t static_value2 = 0x44543de998e53af4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalSensorPinModeRequest";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool direction\n"
;
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DigitalSensorPinModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_arduino_msgs::DigitalSensorPinModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORPINMODEREQUEST_H
