// Generated by gencpp from file ros_arduino_msgs/DigitalSensorRead.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORREAD_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORREAD_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/DigitalSensorReadRequest.h>
#include <ros_arduino_msgs/DigitalSensorReadResponse.h>


namespace ros_arduino_msgs
{

struct DigitalSensorRead
{

typedef DigitalSensorReadRequest Request;
typedef DigitalSensorReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalSensorRead
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorRead > {
  static const char* value()
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorRead&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorRead > {
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalSensorRead";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorRead&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorReadRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorRead >
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorReadRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorRead >
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorReadRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorReadResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorRead >
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorReadResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorRead >
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorReadResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorRead >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORREAD_H
