// Generated by gencpp from file ros_arduino_msgs/Enable.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_ENABLE_H
#define ROS_ARDUINO_MSGS_MESSAGE_ENABLE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/EnableRequest.h>
#include <ros_arduino_msgs/EnableResponse.h>


namespace ros_arduino_msgs
{

struct Enable
{

typedef EnableRequest Request;
typedef EnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Enable
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::Enable > {
  static const char* value()
  {
    return "3ea372bdd9923da8a6c7ae2db934a6cb";
  }

  static const char* value(const ::ros_arduino_msgs::Enable&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::Enable > {
  static const char* value()
  {
    return "ros_arduino_msgs/Enable";
  }

  static const char* value(const ::ros_arduino_msgs::Enable&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::EnableRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::Enable >
template<>
struct MD5Sum< ::ros_arduino_msgs::EnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::Enable >::value();
  }
  static const char* value(const ::ros_arduino_msgs::EnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::EnableRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::Enable >
template<>
struct DataType< ::ros_arduino_msgs::EnableRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::Enable >::value();
  }
  static const char* value(const ::ros_arduino_msgs::EnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::EnableResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::Enable >
template<>
struct MD5Sum< ::ros_arduino_msgs::EnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::Enable >::value();
  }
  static const char* value(const ::ros_arduino_msgs::EnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::EnableResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::Enable >
template<>
struct DataType< ::ros_arduino_msgs::EnableResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::Enable >::value();
  }
  static const char* value(const ::ros_arduino_msgs::EnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_ENABLE_H
