// Generated by gencpp from file ros_arduino_msgs/ServoDetach.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_SERVODETACH_H
#define ROS_ARDUINO_MSGS_MESSAGE_SERVODETACH_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/ServoDetachRequest.h>
#include <ros_arduino_msgs/ServoDetachResponse.h>


namespace ros_arduino_msgs
{

struct ServoDetach
{

typedef ServoDetachRequest Request;
typedef ServoDetachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoDetach
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::ServoDetach > {
  static const char* value()
  {
    return "541b98e964705918fa8eb206b65347b3";
  }

  static const char* value(const ::ros_arduino_msgs::ServoDetach&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::ServoDetach > {
  static const char* value()
  {
    return "ros_arduino_msgs/ServoDetach";
  }

  static const char* value(const ::ros_arduino_msgs::ServoDetach&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::ServoDetachRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::ServoDetach >
template<>
struct MD5Sum< ::ros_arduino_msgs::ServoDetachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::ServoDetach >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoDetachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::ServoDetachRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::ServoDetach >
template<>
struct DataType< ::ros_arduino_msgs::ServoDetachRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::ServoDetach >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoDetachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::ServoDetachResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::ServoDetach >
template<>
struct MD5Sum< ::ros_arduino_msgs::ServoDetachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::ServoDetach >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoDetachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::ServoDetachResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::ServoDetach >
template<>
struct DataType< ::ros_arduino_msgs::ServoDetachResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::ServoDetach >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoDetachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_SERVODETACH_H
