// Generated by gencpp from file ros_arduino_msgs/SetServoSpeed.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_SETSERVOSPEED_H
#define ROS_ARDUINO_MSGS_MESSAGE_SETSERVOSPEED_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/SetServoSpeedRequest.h>
#include <ros_arduino_msgs/SetServoSpeedResponse.h>


namespace ros_arduino_msgs
{

struct SetServoSpeed
{

typedef SetServoSpeedRequest Request;
typedef SetServoSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetServoSpeed
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::SetServoSpeed > {
  static const char* value()
  {
    return "a5bb1b2c3fa1e96327140e230e8115dd";
  }

  static const char* value(const ::ros_arduino_msgs::SetServoSpeed&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::SetServoSpeed > {
  static const char* value()
  {
    return "ros_arduino_msgs/SetServoSpeed";
  }

  static const char* value(const ::ros_arduino_msgs::SetServoSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::SetServoSpeedRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::SetServoSpeed >
template<>
struct MD5Sum< ::ros_arduino_msgs::SetServoSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::SetServoSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetServoSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::SetServoSpeedRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::SetServoSpeed >
template<>
struct DataType< ::ros_arduino_msgs::SetServoSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::SetServoSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetServoSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::SetServoSpeedResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::SetServoSpeed >
template<>
struct MD5Sum< ::ros_arduino_msgs::SetServoSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::SetServoSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetServoSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::SetServoSpeedResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::SetServoSpeed >
template<>
struct DataType< ::ros_arduino_msgs::SetServoSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::SetServoSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetServoSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_SETSERVOSPEED_H
