// Generated by gencpp from file ros_arduino_msgs/SetSpeed.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_SETSPEED_H
#define ROS_ARDUINO_MSGS_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/SetSpeedRequest.h>
#include <ros_arduino_msgs/SetSpeedResponse.h>


namespace ros_arduino_msgs
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::SetSpeed > {
  static const char* value()
  {
    return "ca65bba734a79b4a6707341d829f4d5c";
  }

  static const char* value(const ::ros_arduino_msgs::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::SetSpeed > {
  static const char* value()
  {
    return "ros_arduino_msgs/SetSpeed";
  }

  static const char* value(const ::ros_arduino_msgs::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::SetSpeedRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::SetSpeed >
template<>
struct MD5Sum< ::ros_arduino_msgs::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::SetSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::SetSpeedRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::SetSpeed >
template<>
struct DataType< ::ros_arduino_msgs::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::SetSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::SetSpeedResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::SetSpeed >
template<>
struct MD5Sum< ::ros_arduino_msgs::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::SetSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::SetSpeedResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::SetSpeed >
template<>
struct DataType< ::ros_arduino_msgs::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::SetSpeed >::value();
  }
  static const char* value(const ::ros_arduino_msgs::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_SETSPEED_H
