// Generated by gencpp from file ros_arduino_msgs/UpdatePID.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_UPDATEPID_H
#define ROS_ARDUINO_MSGS_MESSAGE_UPDATEPID_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/UpdatePIDRequest.h>
#include <ros_arduino_msgs/UpdatePIDResponse.h>


namespace ros_arduino_msgs
{

struct UpdatePID
{

typedef UpdatePIDRequest Request;
typedef UpdatePIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdatePID
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::UpdatePID > {
  static const char* value()
  {
    return "81f9af76f898bdd520f26b42602a5eb2";
  }

  static const char* value(const ::ros_arduino_msgs::UpdatePID&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::UpdatePID > {
  static const char* value()
  {
    return "ros_arduino_msgs/UpdatePID";
  }

  static const char* value(const ::ros_arduino_msgs::UpdatePID&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::UpdatePIDRequest> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::UpdatePID >
template<>
struct MD5Sum< ::ros_arduino_msgs::UpdatePIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::UpdatePID >::value();
  }
  static const char* value(const ::ros_arduino_msgs::UpdatePIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::UpdatePIDRequest> should match
// service_traits::DataType< ::ros_arduino_msgs::UpdatePID >
template<>
struct DataType< ::ros_arduino_msgs::UpdatePIDRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::UpdatePID >::value();
  }
  static const char* value(const ::ros_arduino_msgs::UpdatePIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::UpdatePIDResponse> should match
// service_traits::MD5Sum< ::ros_arduino_msgs::UpdatePID >
template<>
struct MD5Sum< ::ros_arduino_msgs::UpdatePIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::UpdatePID >::value();
  }
  static const char* value(const ::ros_arduino_msgs::UpdatePIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::UpdatePIDResponse> should match
// service_traits::DataType< ::ros_arduino_msgs::UpdatePID >
template<>
struct DataType< ::ros_arduino_msgs::UpdatePIDResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::UpdatePID >::value();
  }
  static const char* value(const ::ros_arduino_msgs::UpdatePIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_UPDATEPID_H
